export const HomePageActions = {
  POSTS: 'SET_POSTS',
  SET_LOADING_TRUE: 'SET_LOADING_TRUE',
  SET_LOADING_FALSE: 'SET_LOADING_FALSE',
  SET_DETAIL_LOADING_TRUE: 'SET_DETAIL_LOADING_TRUE',
  SET_DETAIL_LOADING_FALSE: 'SET_DETAIL_LOADING_FALSE',
  PAGE: 'SET_PAGE',
  FINISH_POSTS_TRUE: 'FINISH_POSTS_TRUE',
  FINISH_POSTS_FALSE: 'FINISH_POSTS_FALSE',
  SET_POST_DETAIL: 'SET_POST_DETAIL',
  SET_POST_COMMENTS: 'SET_POST_COMMENTS',
  SET_COMMENT_PAGE: 'SET_COMMENT_PAGE',
  SET_COMMENT_LOADING_TRUE: 'SET_COMMENT_LOADING_TRUE',
  SET_COMMENT_LOADING_FALSE: 'SET_COMMENT_LOADING_FALSE',
  FINISH_COMMENTS_TRUE: 'FINISH_COMMENTS_TRUE',
  FINISH_COMMENTS_FALSE: 'FINISH_COMMENTS_FALSE',
};

export const UsersActions = {
  SET_USERS: 'SET_USERS',
  SET_USER_LOADING_TRUE:'SET_USER_LOADING_TRUE',
  SET_USER_LOADING_FALSE:'SET_USER_LOADING_FALSE'
};


export const AlbumsActions = {
  SET_ALBUMS: 'SET_ALBUMS',
};
